# Generated by Django 3.2.7 on 2021-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productname_capitalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
